### ISSUE TITLE
Weekly Meeting Action Items

### ISSUE THREAD

**Issue by delgrecoj** [delgrecoj/LibWorkInstructions#2]
This thread will capture action items that arise from the weekly meetings, so we're all on the same page.

**Comment by delgrecoj** [comment]
Weekly meetings scheduled for Thursdays 8:00am-9:00am at Acutec, in our CI office.

**Comment by delgrecoj** [comment]
action items for next week:
- defining data classes for each type of object in requirements doc
- everyone able to open/build the project

**Comment by delgrecoj** [comment]
for next week: showcase of real-world C# code

**Comment by delgrecoj** [comment]
action items for next week:
- buildable with dotnetcore3.1sdk on everyone's laptops
- changes to data modeling regarding revisions, ids, pools, etc.

likely action items for following week:
- automated testing framework setup and working
- requirements translated into testcases (TDD?)

**Comment by delgrecoj** [comment]
action items for next week:
* Jesse to get nunit working (today)
* Changes to business logic to match new data models
* Draft testcases following the requirements

**Comment by delgrecoj** [comment]
@WesleyL30 , @ColemanKobe  I've pushed a working nunit testing setup to your `Interns` branch.  May require a Nuget package restore, but you should be able to build everything in VS and run the tests through the Test menu also in VS.  I've left a partial example testcase that does some setup with mock data as a starting place, feel free to rip that out or abstract it however you guys see fit.

![image](https://user-images.githubusercontent.com/21695244/135471392-644fa145-a933-4630-81e6-9a765729e791.png)

**Comment by delgrecoj** [comment]
action items for next week:
- test cases implemented for half of the requirements bullet points
- partial to completed implementation of audit log capabilities
- pull request submitted with these changes for review by CI team

**Comment by delgrecoj** [comment]
action items for next week:
- test cases implemented for remainder of the requirements
- (carry-over) pull request submitted with these changes for review by CI team
- robustness improvements wrt input validations and throwing exceptions on malformed inputs

**Comment by delgrecoj** [comment]
action items for next week:
- Jesse to review that PR in more depth
- address points of review from that PR
- have code follow a consistent style-guide
- (carry-over) throwing exceptions on invalid inputs
- revise event struct to store args in (argname, argjson) representation

**Comment by delgrecoj** [comment]
(just noting my action-item above is complete)

**Comment by delgrecoj** [comment]
action items for next week:
- (carry-over) have code follow a consistent style-guide
- revise method signatures to take in appropriate parameters
  - (content of WI, op WI goes with, etc, when creating)
  - (content of WI to revise, when revising)
  - (WIs each link to exactly one op, which in turn links to exactly one rev of one job)
  - (pulling appropriate WI reqs being fed the job, job-rev, and opservice (e.g. "F110", "A", "50"))
- revise test cases for existing methods, to align with reqs doc

**Comment by aalloway01** [comment]
Action Items for next week (2021/11/11)

- [x] (carry over) continue to revise method signatures
- [x] (carry over) continue to revise test cases for correctness
- [x] enumerate all methods that should exist (using diagram as reference)

**Comment by delgrecoj** [comment]
Docket for the remaining meetings:
- Nov18
  - Interns team to revise `MergeQualityClauseRevsBasedOnQualityClause/2`
  - Interns team to finish revising prior methods (switching to linq/iterators, etc)
  - Interns team to have majority if not entirety of the remaining functions implemented
  - CI team to seek information on assessment/syllabus from professor
- Nov25
  - Interns team to have tests written for the entirety of the methods
  - CI team to subsequently review the testcases
- Dec2
  - Interns team to have summary/readme and usage/inline documentation written
  - CI team to subsequently review the documentation
- Dec9
  - Post-mortem; what went well, what didn't go well, clarity on any outstanding questions, etc.
  - Address any assessment requirements per the syllabus
  - CI to migrate the `LibWorkInstructions` repository to a dedicated Acutec organization

**Comment by delgrecoj** [comment]
@WesleyL30, @ColemanKobe we just noticed that the Nov25 meeting would fall on thanksgiving which we have off; is there a different day that week that we could meet instead?  What's the thanksgiving vacation situation for Allegheny look like (I know they have changed from prior years)?

**Comment by ColemanKobe** [comment]
For Allegheny, the entire week is thanksgiving break. We can possibly meet virtually or just skip that particular meeting and combine the action items for the thanksgiving week and the week after that.

**Comment by delgrecoj** [comment]
Let's go for the latter; action items listed above for Nov25 are to be merged into the Dec2 meeting.

**Comment by WesleyL30** [comment]
@delgrecoj @aalloway01  For our meeting tomorrow how should I go about joining?  I'm currently in Isolation until Friday.  Is there a way to possibly have a virtual portion tomorrow so I am able to attend?

**Comment by delgrecoj** [comment]
Yes, please coordinate with @ColemanKobe to do some kind of screenshare/videochat thing (maybe Google Hangouts, he'll have better luck on the college wifi than us with our phones); if that doesn't pan out we'll fall back to a phonecall on speaker.
