### ISSUE TITLE
Example Question Thread

### ISSUE THREAD

**Issue by delgrecoj** [delgrecoj/LibWorkInstructions#3]
Intention is to create issues to cover question/answer back and forths between the students and Acutec staff, so it's all more structured and searchable/discoverable to everyone afterwards; these issues would get tagged with the "question" label and closed when resolved.

**Comment by ColemanKobe** [comment]
For the management aspect of the requirements gathering, would it be better for us to use methods that actually change the database or return a query of the changed database in some form?

**Comment by aalloway01** [comment]
The plan is to modify the object in memory. The methods you write will mutate that object like changing properties on that object or adding to the list of jobs, etc. You only have to return something from the methods if there is something meaningful to return.

**Comment by aalloway01** [comment]
Most of the methods could probably be void because you don't have to return anything. If the methods have exception handling then the "database transaction" would be either success and proceed to the next method (query) or fail because of exception.

**Comment by ColemanKobe** [comment]
If users don't have a console when `Console.Write` is used, how do we display the latest version of the work instructions or have the prior revisions of a work instruction/spec/clause?

**Comment by delgrecoj** [comment]
Keep in mind, this is a library; the "users" are other devs calling into this library from their environment (likely from an HTTP API).  Returning the data in some return type other than `void` should do the trick; displaying it to the end-users isn't in-scope for this project, but returning the appropriate information is.

**Comment by ColemanKobe** [comment]
Just wanted to get some clarification... if a work instruction is tied to one revision of an operation, and there's a list of operations for a particular job, why would `JobRefToWorkInstructionRefs` have a `List<List<int>>` instead of just `List<int>`?

**Comment by delgrecoj** [comment]
```
public Dictionary<string, List<List<Guid>>> JobRefToWorkInstructionRefs = new Dictionary<string, List<List<Guid>>>();
```

I would interpret the above (pulled from current `Interns` branch head) to be that `JobRefToWorkInstructionRefs` is a map from a reference to the job to a list of lists of workinstruction references; the outer list representing operations on that job, and the inner list representing revisions of that workinstruction.  Whether that representation of the data is correct or whether you want to use a different representation of the data, is something I'd consider within your problem domain to decide.

As far as relationships between these objects and revisions thereof, maybe this description will be clearer than how it's described in the requirements document;

- a `job` has many `jobrev`s
- a `jobrev` has many `op`s
- an `op` has one `wi` (workinstruction)
- a `wi` has many `wirev`s

Thus to walk through in reverse,

- a `wirev` has one `wi`
- a `wi` has one `op`
- an `op` has one `jobrev`
- a `jobrev` has one `job`

**Comment by delgrecoj** [comment]
Here's a visual that includes the quality clause and operational specifications and their respective revisions; 

![image](https://user-images.githubusercontent.com/21695244/139912724-828c12ca-8396-4e98-a377-3a1371f7c1c4.png)

**Comment by aalloway01** [comment]
![Untitled](https://user-images.githubusercontent.com/57716294/140315235-7961d635-10d2-410b-8ae9-e5969900210e.png)

**Comment by ColemanKobe** [comment]
How should we go about revising `MergeQualityClauseRevsBasedOnQualityClause/2`? You said something about sequences, but could you elaborate further on that?

**Comment by delgrecoj** [comment]
Revisions would have a sequence field to track the order the revisions were created in, if you're merging those sequences from two sets you'll get duplicate sequence numbers which doesn't logically make sense, i.e. two seq-0 revisions, two seq-1 revisions, one seq-2 revision, how would one tell what order the prior revisions happened in?

**Comment by ColemanKobe** [comment]
So shouldn't `UpdateJob` and `CreateJobRev` do the same thing? If so, should we delete one of them? Would the same also apply for quality clause, work instruction, and op revs?

**Comment by delgrecoj** [comment]
As mentioned in the meeting, they would be different if there was metadata about the job being tracked to update but that was an oversight in the requirements doc so we won't hold to that; it's acceptable to drop the `UpdateJob` one.  Quality clauses similarly weren't described to contain any metadata in the requirements doc so you wouldn't need an `Update` method for those, nor operations themselves, but the operational specifications and work instructions did have fields specified so those need both an update and revision method.
